### PR TITLE
Script/swagger merge tool

### PR DESCRIPTION
**Pull request by maruf0011**
Script will combine lcd swagger and fcd swagger into a single swagger file.

### CODE REVIEW

**Comment by hanjukim** [comment]
I will merge this PR after we verify that it works well on the API Gateway.

**Comment by etienne-napoleone** [comment]
I'll check thanks

**Comment by etienne-napoleone** [comment]
small problem for api-gateway:
```
Unable to create resource at path '/slashing/validators/{validatorPubKey}/signing_info': A sibling ({validatorAddr}) of this resource already has a variable path part -- only one is allowed 
```
Manually changing `validatorPubKey` to `validatorAddr` fixed it so should not be a big change

Screen Shot 2020-06-11 at 21 27 17

**Comment by etienne-napoleone** [comment]
Last version transited by @maruf0011 works correctly on api-gateway

**Pull request merged**
